# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_training_video_field_tweaks"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingvideo",
            name="transcript_paragraph_starts",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Integer start seconds per transcript paragraph (split by blank lines), "
                    "from YouTube caption timing — not embedded in transcript text."
                ),
            ),
        ),
    ]
