# Generated by Django 5.2.14 on 2026-05-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='isbn',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='metadata_lookup_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='metadata_lookup_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='raw_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
